version: 1.1.{build}
before_build:
- ps: nuget restore SmallerImages.sln
build:
  project: SmallerImages/SmallerImages.csproj
  publish_nuget: true
  verbosity: minimal

artifacts:
  path: C:\projects\smallerimages\SmallerImages\bin\Debug\SmallerImages.dll
